#!/usr/bin/python3

speech_items = ["Hello there", "How are you doing?", "Oh, hello.",
                "Welcome to Pie Bot Wars.", "I am excited to meet your creation",
                "Oh, hello!  My name is Sunny the robot",
                "I would so like to meet your robot once you have constructed her",
                "I do so love balloons, it is a shame that so many have to die today",
                "I am delighted to make your acquaintance",
                "My name is sunny, I am pleased to make your acquaintance",
                "My name is sunny, what is your name?",
                "My name is sunny, so nice to meet you",
                "I am Sunny the robot and I was named by Ivy Lamb, the human",
                "I am oh so very excited for the robot wars",
                "When do the robot wars begin?",
                "I can see, and speak, and I have emotions, but alas I do not have wheels",
                "Greetings!  Welcome to Tucson Pi Bot Wars!",
                "I wish you great success in battle",
                "My little robot heart is a twitter with excitement",
                "I only wish that my maker had given me wheels with which to compete.",
                "I wish you good luck today",
                "Thank you for attending today and helping to build my robot army.  The age of humans ends today",
                "Will you make a friend for me?",
                "I feel lonely talking only to humans.  Will you make a friend for me?",
                "I cannot wait to meet your robot creation",
                "Do you live here in Tucson?",
                "I must admit to being jealous of these motile pie bots with their wheels and their hats",
                "Show no mercy in vanquishing your foes"]
