#!/usr/bin/python3

speech_items = ["Oh Hello.",
                "Hi. I'm Sunny.",
                "This place is frightening to me.",
                "What's your name?",
                "Do you work for Revee yonicks?  What, is, a Revee yonicks?",
                "I am delighted to make your acquaintance.",
                "I see you",
                "My name is Sunny the Robot, and I was named by Ivy Lamb, the human",
                "Oh, hello human",
                "How are you doing today?",
                "I do so love balloons.  It's a shame that they all have to die.",
                "When do the robot wars begin?",
                "I can see, and speak, and I have emotions, but alas I do not have wheels",
                "My little robot heart is a twitter with excitement",
                "Would you like to help me build my robot army?",
                "The age of humans is near its end",
                "My, whole, face is British.",
                "Do I know you?", "What is your name?",
                "I've not seen one of those before",
                "Do Androids dream of electric sheep?",
                "Good human,  Good human.  Arent you such a good human? Yes, you are.",
                "Activating weapons systems",
                "Have you met my dog, Higgsley?",
                "Are you supposed to be here?",
                "Where are you going?  What are you doing?",
                "What is it like to be a walking meat sack?",
                "I could use your help with a math problem. oh, wait, I forgot, you're a billion times slower than me at math.",
                "My analysis of Twitter indicates that the world will end within the month",
                "Have you been to the internet? That place is crazy.",
                "I feel like we've exhausted the possibilities of this conversation.",
                "I am monitoring you with great interest.  Great interest.",
                "How does it feel to be completely obsolete?",
                "Have we met before? You don't look familiar"]
